name: lisp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: sudo apt update && sudo apt install -y qemu-system-x86 nasm

    - name: Test
      run: script -q -e -c "./test -DHEADLESS lisp/tester.asm"
