name: lisp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: [ "linux/amd64", "linux/386" ]

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.17'

    - name: Test
      run: ./test -DHEADLESS lisp/tester.asm
